export const INCREASE = 'INCREASE';
export const DECREASE = 'DECREASE';
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
export const GET_ALL_POSTS = 'GET_ALL_POSTS';
export const GET_CATEGORY_POSTS = 'GET_CATEGORY_POSTS';
export const SET_SORT_TYPE = 'SET_SORT_TYPE';
